# -*- encoding: utf-8 -*-
# Copyright 2012 Citrix Systems, Inc. Licensed under the
# Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License.  Citrix Systems, Inc.
# reserves all rights not expressly granted by the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Automatically generated by addcopyright.py at 04/03/2012
""" P1 tests for tags
"""
#Import Local Modules
import marvin
from nose.plugins.attrib import attr
from marvin.cloudstackTestCase import *
from marvin.cloudstackAPI import *
from integration.lib.utils import *
from integration.lib.base import *
from integration.lib.common import *
import datetime


class Services:
    """Test tags Services
    """

    def __init__(self):
        self.services = {
                        "domain": {
                                   "name": "Domain",
                        },
                        "project": {
                                    "name": "Project",
                                    "displaytext": "Test project",
                        },
                        "account": {
                                    "email": "administrator@clogeny.com",
                                    "firstname": "Test",
                                    "lastname": "User",
                                    "username": "test",
                                    # Random characters are appended for unique
                                    # username
                                    "password": "password",
                         },
                         "user": {
                                    "email": "administrator@clogeny.com",
                                    "firstname": "User",
                                    "lastname": "User",
                                    "username": "User",
                                    # Random characters are appended for unique
                                    # username
                                    "password": "password",
                         },
                         "service_offering": {
                                    "name": "Tiny Instance",
                                    "displaytext": "Tiny Instance",
                                    "cpunumber": 1,
                                    "cpuspeed": 100,
                                    # in MHz
                                    "memory": 64,
                                    # In MBs
                        },
                        "disk_offering": {
                                    "displaytext": "Tiny Disk Offering",
                                    "name": "Tiny Disk Offering",
                                    "disksize": 1
                        },
                        "volume": {
                                   "diskname": "Test Volume",
                        },
                        "virtual_machine": {
                                    "displayname": "TestVM",
                                    "username": "root",
                                    "password": "password",
                                    "ssh_port": 22,
                                    "hypervisor": 'XenServer',
                                    "privateport": 22,
                                    "publicport": 22,
                                    "protocol": 'TCP',
                        },
                        "template": {
                                    "displaytext": "Cent OS Template",
                                    "name": "Cent OS Template",
                                    "ostypeid": 'e756b7cd-cf25-41d1-8bf0-8c68d96d36c6',
                                    "templatefilter": 'self',
                        },
                        "iso":
                        {
                            "displaytext": "CentOS 5.3x64 ISO",
                            "name": "CentOS 5.3x64 ISO",
                            "url": "http://iso.linuxquestions.org/download/504/1819/http/gd4.tuwien.ac.at/dsl-4.4.10.iso",
                            # Source URL where ISO is located
                            "isextractable": True,
                            "isfeatured": True,
                            "ispublic": True,
                            "ostypeid": 'e756b7cd-cf25-41d1-8bf0-8c68d96d36c6',
                            "mode": 'HTTP_DOWNLOAD',
                            # Used in Extract template, value must be HTTP_DOWNLOAD
                        },
                        "network_offering": {
                                    "name": 'Network offering-VR services',
                                    "displaytext": 'Network offering-VR services',
                                    "guestiptype": 'Isolated',
                                    "supportedservices": 'Dhcp,Dns,SourceNat,PortForwarding,Vpn,Firewall,Lb,UserData,StaticNat',
                                    "traffictype": 'GUEST',
                                    "availability": 'Optional',
                                    "serviceProviderList": {
                                            "Dhcp": 'VirtualRouter',
                                            "Dns": 'VirtualRouter',
                                            "SourceNat": 'VirtualRouter',
                                            "PortForwarding": 'VirtualRouter',
                                            "Vpn": 'VirtualRouter',
                                            "Firewall": 'VirtualRouter',
                                            "Lb": 'VirtualRouter',
                                            "UserData": 'VirtualRouter',
                                            "StaticNat": 'VirtualRouter',
                                        },
                                    },
                         "network": {
                                  "name": "Test Network",
                                  "displaytext": "Test Network",
                                },
                         "lbrule": {
                                    "name": "SSH",
                                    "alg": "leastconn",
                                    # Algorithm used for load balancing
                                    "privateport": 22,
                                    "publicport": 22,
                                    "openfirewall": False,
                         },
                         "natrule": {
                                    "privateport": 22,
                                    "publicport": 22,
                                    "protocol": "TCP"
                                },
                         "fw_rule": {
                                    "startport": 1,
                                    "endport": 6000,
                                    "cidr": '55.55.0.0/11',
                                    # Any network (For creating FW rule)
                                },
                         "security_group": {
                                    "name": 'SSH',
                                    "protocol": 'TCP',
                                    "startport": 22,
                                    "endport": 22,
                                    "cidrlist": '0.0.0.0/0',
                        },
                        "ostypeid": 'e756b7cd-cf25-41d1-8bf0-8c68d96d36c6',
                        # Cent OS 5.3 (64 bit)
                        "sleep": 60,
                        "timeout": 10,
                        "mode": 'advanced',
                    }


class TestResourceTags(cloudstackTestCase):

    @classmethod
    def setUpClass(cls):
        cls.api_client = super(
                               TestResourceTags,
                               cls
                               ).getClsTestClient().getApiClient()
        cls.services = Services().services
        # Get Zone
        cls.zone = get_zone(cls.api_client, cls.services)

        # Create domains, account etc.
        cls.domain = get_domain(cls.api_client, cls.services)

        cls.account = Account.create(
                            cls.api_client,
                            cls.services["account"],
                            admin=True,
                            domainid=cls.domain.id
                            )
        cls.zone = get_zone(cls.api_client, cls.services)

        cls.template = get_template(
                            cls.api_client,
                            cls.zone.id,
                            cls.services["ostypeid"]
                            )

        # Create service offerings, disk offerings etc
        cls.service_offering = ServiceOffering.create(
                                    cls.api_client,
                                    cls.services["service_offering"]
                                    )

        cls.disk_offering = DiskOffering.create(
                                    cls.api_client,
                                    cls.services["disk_offering"]
                                    )

        cls.services["virtual_machine"]["zoneid"] = cls.zone.id
        cls.services["virtual_machine"]["template"] = cls.template.id
        cls.vm_1 = VirtualMachine.create(
                                    cls.api_client,
                                    cls.services["virtual_machine"],
                                    accountid=cls.account.account.name,
                                    domainid=cls.account.account.domainid,
                                    serviceofferingid=cls.service_offering.id,
                                    mode=cls.zone.networktype
                                )
        cls.vm_2 = VirtualMachine.create(
                                    cls.api_client,
                                    cls.services["virtual_machine"],
                                    accountid=cls.account.account.name,
                                    domainid=cls.account.account.domainid,
                                    serviceofferingid=cls.service_offering.id,
                                    mode=cls.zone.networktype
                                )
        cls._cleanup = [
                        cls.account,
                        cls.service_offering,
                        cls.disk_offering
                        ]
        return

    @classmethod
    def tearDownClass(cls):
        try:
            #Cleanup resources used
            cleanup_resources(cls.api_client, cls._cleanup)
        except Exception as e:
            raise Exception("Warning: Exception during cleanup : %s" % e)
        return

    def setUp(self):
        self.apiclient = self.testClient.getApiClient()
        self.dbclient = self.testClient.getDbConnection()
        self.cleanup = []
        return

    def tearDown(self):
        try:
            #Clean up, terminate the created accounts, domains etc
            cleanup_resources(self.apiclient, self.cleanup)
        except Exception as e:
            raise Exception("Warning: Exception during cleanup : %s" % e)
        return

    @attr(tags=["advanced"])
    def test_01_lbrule_tag(self):
        """ Test Create tag on LB rule and remove the LB rule
        """
        # Validate the following
        # 1. Configured LB rule by assigning 2vms
        # 2. create Tag on LB rule using CreateTag API
        #  3. Delete the LB rule

        self.debug("Fetching the network details for account: %s" %
                                                self.account.account.name)
        networks = Network.list(
                                self.apiclient,
                                account=self.account.account.name,
                                domainid=self.account.account.domainid,
                                listall=True
                                )
        self.assertEqual(
                         isinstance(networks, list),
                         True,
                         "List networks should not return an empty response"
                         )
        network = networks[0]
        self.debug("Network for the account: %s is %s" %
                                    (self.account.account.name, network.name))

        self.debug("Associating public IP for network: %s" % network.id)
        public_ip = PublicIPAddress.create(
                                    self.apiclient,
                                    accountid=self.account.account.name,
                                    zoneid=self.zone.id,
                                    domainid=self.account.account.domainid,
                                    networkid=network.id
                                    )
        self.cleanup.append(public_ip)

        self.debug("Trying to create LB rule on IP: %s" %
                                    public_ip.ipaddress.ipaddress)

        # Create Load Balancer rule on the public ip
        lb_rule = LoadBalancerRule.create(
                                    self.apiclient,
                                    self.services["lbrule"],
                                    ipaddressid=public_ip.ipaddress.id,
                                    accountid=self.account.account.name
                                    )

        # Check if the LB rule created successfully
        lb_rules = LoadBalancerRule.list(
                                         self.apiclient,
                                         id=lb_rule.id
                                         )

        self.assertEqual(
                         isinstance(lb_rules, list),
                         True,
                         "List LB rules should return valid list"
                         )

        self.debug("Assigning the virtual machines (%s, %s) to lb rule: %s" %
                                                        (self.vm_1.name,
                                                         self.vm_2.name,
                                                         lb_rule.name))

        lb_rule.assign(self.apiclient, [self.vm_1, self.vm_2])
        self.debug("Creating a tag for load balancer rule")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=lb_rule.id,
                         resourceType='LoadBalancer',
                         tags={'LB': 40}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='LoadBalancer',
                        key='LB',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        value=40
                        )

        self.debug("Tag created: %s" % str(tags))
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         int(tags[0].value),
                         40,
                         "The tag value should match with the original value"
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=lb_rule.id,
                       resourceType='LoadBalancer',
                       tags={'LB': 40}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='LoadBalancer',
                        key='LB',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid
                        )

        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )

        self.debug("Deleting the Load balancer rule")
        try:
            lb_rule.delete(self.apiclient)
        except Exception as e:
            self.fail("failed to delete load balancer rule! - %s" % e)
        return

    @attr(tags=["advanced"])
    def test_02_natrule_tag(self):
        """ Test Create tag on nat rule and remove the nat rule
        """
        # Validate the following
        # 1. Configured PF rule
        # 2. create Tag on PF rule  using CreateTag API
        # 3. Delete the PF rule

        self.debug("Fetching the network details for account: %s" %
                                                self.account.account.name)
        networks = Network.list(
                                self.apiclient,
                                account=self.account.account.name,
                                domainid=self.account.account.domainid,
                                listall=True
                                )
        self.assertEqual(
                         isinstance(networks, list),
                         True,
                         "List networks should not return an empty response"
                         )
        network = networks[0]
        self.debug("Network for the account: %s is %s" %
                                    (self.account.account.name, network.name))

        self.debug("Associating public IP for network: %s" % network.id)
        public_ip = PublicIPAddress.create(
                                    self.apiclient,
                                    accountid=self.account.account.name,
                                    zoneid=self.zone.id,
                                    domainid=self.account.account.domainid,
                                    networkid=network.id
                                    )
        self.cleanup.append(public_ip)

        self.debug("Trying to create LB rule on IP: %s" %
                                    public_ip.ipaddress.ipaddress)

        self.debug("Creating PF rule for vm: %s on Ip: %s" %
                            (self.vm_1.name, public_ip.ipaddress.ipaddress))

        nat_rule = NATRule.create(
                         self.apiclient,
                         self.vm_1,
                         self.services["natrule"],
                         ipaddressid=public_ip.ipaddress.id
                      )

        # Check if NAT rule created successfully
        nat_rules = NATRule.list(
                                 self.apiclient,
                                 id=nat_rule.id
                                 )

        self.assertEqual(
                         isinstance(nat_rules, list),
                         True,
                         "List NAT rules should return valid list"
                         )

        self.debug("Creating a tag for port forwarding rule")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=nat_rule.id,
                         resourceType='portForwardingRule',
                         tags={'PF': 40}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='portForwardingRule',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='PF',
                        value=40
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         int(tags[0].value),
                         40,
                         "The tag value should match with the original value"
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=nat_rule.id,
                       resourceType='portForwardingRule',
                       tags={'PF': 40}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='portForwardingRule',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='PF',
                        value=40
                        )

        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        self.debug("Deleting the port forwarding rule")
        try:
            nat_rule.delete(self.apiclient)
        except Exception as e:
            self.fail("failed to delete port forwarding rule! - %s" % e)
        return

    @attr(tags=["advanced"])
    def test_03_firewallrule_tag(self):
        """ Test Create tag on firewall rule and remove the firewall rule
        """
        # Validate the following
        # 1. Configured firewall rule
        # 2. create Tag on firewall rule  using CreateTag API
        # 3. Delete the firewall rule

        self.debug("Fetching the network details for account: %s" %
                                                self.account.account.name)
        networks = Network.list(
                                self.apiclient,
                                account=self.account.account.name,
                                domainid=self.account.account.domainid,
                                listall=True
                                )
        self.assertEqual(
                         isinstance(networks, list),
                         True,
                         "List networks should not return an empty response"
                         )
        network = networks[0]
        self.debug("Network for the account: %s is %s" %
                                    (self.account.account.name, network.name))

        self.debug("Associating public IP for network: %s" % network.id)
        public_ip = PublicIPAddress.create(
                                    self.apiclient,
                                    accountid=self.account.account.name,
                                    zoneid=self.zone.id,
                                    domainid=self.account.account.domainid,
                                    networkid=network.id
                                    )
        self.cleanup.append(public_ip)

        self.debug("Creating firewall rule on public IP: %s" %
                                                public_ip.ipaddress.ipaddress)
        #Create Firewall rule on public IP
        fw_rule = FireWallRule.create(
                            self.apiclient,
                            ipaddressid=public_ip.ipaddress.id,
                            protocol='TCP',
                            cidrlist=[self.services["fw_rule"]["cidr"]],
                            startport=self.services["fw_rule"]["startport"],
                            endport=self.services["fw_rule"]["endport"]
                            )

        self.debug("Created firewall rule: %s" % fw_rule.id)

        fw_rules = FireWallRule.list(
                                     self.apiclient,
                                     id=fw_rule.id
                                    )
        self.assertEqual(
                         isinstance(fw_rules, list),
                         True,
                         "List fw rules should return a valid firewall rules"
                         )

        self.assertNotEqual(
                            len(fw_rules),
                            0,
                            "Length of fw rules response should not be zero"
                            )

        self.debug("Creating a tag for firewall rule")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=fw_rule.id,
                         resourceType='FirewallRule',
                         tags={'FW': 40}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='FirewallRule',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='FW',
                        value=40
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         40,
                         "The tag value should match with the original value"
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=fw_rule.id,
                       resourceType='FirewallRule',
                       tags={'FW': 40}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='FirewallRule',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='FW',
                        value=40
                        )

        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )

        self.debug("Deleting the firewall rule")
        try:
            fw_rule.delete(self.apiclient)
        except Exception as e:
            self.fail("failed to delete firewall rule! - %s" % e)
        return

    @attr(tags=["advanced"])
    def test_04_vpn_tag(self):
        """ Test Create tag on vpn and remove the vpn
        """
        # Validate the following
        # 1. Enable the VPN
        # 2. create Tag on VPN rule using CreateTag API
        # 3. Delete the VPN rule

        self.debug("Fetching the network details for account: %s" %
                                                self.account.account.name)
        networks = Network.list(
                                self.apiclient,
                                account=self.account.account.name,
                                domainid=self.account.account.domainid,
                                listall=True
                                )
        self.assertEqual(
                         isinstance(networks, list),
                         True,
                         "List networks should not return an empty response"
                         )
        network = networks[0]
        self.debug("Network for the account: %s is %s" %
                                    (self.account.account.name, network.name))

        self.debug("Associating public IP for network: %s" % network.id)
        public_ip = PublicIPAddress.create(
                                    self.apiclient,
                                    accountid=self.account.account.name,
                                    zoneid=self.zone.id,
                                    domainid=self.account.account.domainid,
                                    networkid=network.id
                                    )
        self.cleanup.append(public_ip)

        # User should be able to enable VPN on source NAT
        self.debug("Creating VPN with public NAT IP: %s" %
                                            public_ip.ipaddress.ipaddress)
        # Assign VPN to source NAT
        vpn = Vpn.create(
                        self.apiclient,
                        public_ip.ipaddress.id,
                        account=self.account.account.name,
                        domainid=self.account.account.domainid
                        )

        vpns = Vpn.list(
                        self.apiclient,
                        publicipid=public_ip.ipaddress.id,
                        listall=True,
                        )

        self.assertEqual(
                         isinstance(vpns, list),
                         True,
                         "List VPNs should return a valid VPN list"
                         )

        self.assertNotEqual(
                            len(vpns),
                            0,
                            "Length of list VPN response should not be zero"
                            )

        self.debug("Creating a tag for VPN rule")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=vpn.id,
                         resourceType='VPN',
                         tags={'protocol': 'L2TP'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='VPN',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='protocol',
                        value='L2TP'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'L2TP',
                         "The tag value should match with the original value"
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=vpn.id,
                       resourceType='VPN',
                       tags={'protocol': 'L2TP'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='VPN',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='protocol',
                        value='L2TP'
                        )

        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )

        self.debug("Disabling the VPN")
        try:
            vpn.delete(self.apiclient)
        except Exception as e:
            self.fail("failed to disable VPN! - %s" % e)
        return

    @attr(tags=["advanced", "basic"])
    def test_05_vm_tag(self):
        """ Test Delete tags on UserVM
        """
        # Validate the following
        # 1.Create  a tag on VM using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'India',
                         "The tag value should match with the original value"
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_06_template_tag(self):
        """ Test Delete tags on UserVM
        """
        # Validate the following
        # 1.Create  a tag on template/ISO using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Stopping the virtual machine: %s" % self.vm_1.name)
        #Stop virtual machine
        self.vm_1.stop(self.apiclient)

        timeout = self.services["timeout"]
        #Wait before server has be successfully stopped
        time.sleep(self.services["sleep"])

        while True:
            list_volume = Volume.list(
                                   self.apiclient,
                                   virtualmachineid=self.vm_1.id,
                                   type='ROOT',
                                   listall=True
                                   )
            if isinstance(list_volume, list):
                break
            elif timeout == 0:
                raise Exception("List volumes failed.")

            time.sleep(5)
            timeout = timeout - 1

        self.volume = list_volume[0]

        self.debug("Creating template from ROOT disk of virtual machine: %s" %
                                                            self.vm_1.name)
        #Create template from volume
        template = Template.create(
                                    self.apiclient,
                                    self.services["template"],
                                    self.volume.id
                                )
        self.cleanup.append(template)
        self.debug("Created the template(%s). Now restarting the userVm: %s" %
                                            (template.name, self.vm_1.name))
        self.vm_1.start(self.apiclient)

        self.debug("Creating a tag for the template")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=template.id,
                         resourceType='Template',
                         tags={'OS': 'CentOS'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='Template',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='OS',
                        value='CentOS'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'CentOS',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=template.id,
                       resourceType='Template',
                       tags={'OS': 'CentOS'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='Template',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='OS',
                        value='CentOS'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_07_iso_tag(self):
        """ Test Delete tags on ISO
        """
        # Validate the following
        # 1.Create  a tag on template/ISO using createTags API
        # 2.delete above created tag using deleteTags API

        iso = Iso.create(
                         self.apiclient,
                         self.services["iso"],
                         account=self.account.account.name,
                         domainid=self.account.account.domainid
                         )
        self.debug("ISO created with ID: %s" % iso.id)

        try:
            iso.download(self.apiclient)
            self.cleanup.append(iso)
        except Exception as e:
            self.fail("Exception while downloading ISO %s: %s"\
                      % (iso.id, e))

        list_iso_response = list_isos(
                                      self.apiclient,
                                      id=iso.id
                                      )
        self.assertEqual(
                            isinstance(list_iso_response, list),
                            True,
                            "Check list response returns a valid list"
                        )

        self.debug("Creating a tag for the ISO")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=iso.id,
                         resourceType='ISO',
                         tags={'OS': 'CentOS'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='ISO',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='OS',
                        value='CentOS'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'CentOS',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=iso.id,
                       resourceType='ISO',
                       tags={'OS': 'CentOS'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='ISO',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='OS',
                        value='CentOS'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_08_volume_tag(self):
        """ Test Delete tags on volume
        """
        # Validate the following
        # 1.Create  a tag on volume using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Creating volume for account: %s " %
                                                self.account.account.name)
        volume = Volume.create(
                                   self.apiclient,
                                   self.services["volume"],
                                   zoneid=self.zone.id,
                                   account=self.account.account.name,
                                   domainid=self.account.account.domainid,
                                   diskofferingid=self.disk_offering.id
                                   )
        self.cleanup.append(volume)

        self.debug("Volume created in account: %s" % volume.name)

        self.debug("Creating a tag for the volume")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=volume.id,
                         resourceType='volume',
                         tags={'region': 'india'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='volume',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='india'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'india',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=volume.id,
                       resourceType='ISO',
                       tags={'OS': 'CentOS'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='volume',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_09_snapshot_tag(self):
        """ Test Delete tags on snapshot
        """
        # Validate the following
        # 1.Create  a tag on snapshot using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Creating snapshot on ROOT volume for VM: %s " %
                                                            self.vm_1.name)
        # Get the Root disk of VM
        volumes = list_volumes(
                            self.apiclient,
                            virtualmachineid=self.vm_1.id,
                            type='ROOT',
                            listall=True
                            )
        volume = volumes[0]

        # Create a snapshot from the ROOTDISK
        snapshot = Snapshot.create(self.apiclient, volume.id)
        self.debug("Snapshot created: ID - %s" % snapshot.id)
        self.cleanup.append(snapshot)

        snapshots = list_snapshots(
                                   self.apiclient,
                                   id=snapshot.id
                                   )
        self.assertEqual(
                            isinstance(snapshots, list),
                            True,
                            "Check list response returns a valid list"
                        )

        self.debug("Creating a tag for the snapshot")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=snapshot.id,
                         resourceType='snapshot',
                         tags={'type': 'manual'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='snapshot',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='type',
                        value='manual'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'manual',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=snapshot.id,
                       resourceType='snapshot',
                       tags={'type': 'manual'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='snapshot',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='type',
                        value='manual'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )

        return

    @attr(tags=["advanced"])
    def test_10_network_tag(self):
        """ Test Create tag on guest network
        """
        # Validate the following
        # 1.Create  a tag on GuestNetwork using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Fetching the network details for account: %s" %
                                                self.account.account.name)
        networks = Network.list(
                                self.apiclient,
                                account=self.account.account.name,
                                domainid=self.account.account.domainid,
                                listall=True
                                )
        self.assertEqual(
                         isinstance(networks, list),
                         True,
                         "List networks should not return an empty response"
                         )
        network = networks[0]
        self.debug("Network for the account: %s is %s" %
                                    (self.account.account.name, network.name))

        self.debug("Creating a tag for load balancer rule")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=network.id,
                         resourceType='GuestNetwork',
                         tags={'region': 'india'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='GuestNetwork',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='india'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'india',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=network.id,
                       resourceType='GuestNetwork',
                       tags={'region': 'india'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='GuestNetwork',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='india'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["basic", "sg"])
    def test_11_sec_grp_tag(self):
        """ Test Delete tags on UserVM
        """
        # Validate the following
        # 1.Create  a tag on VM using createTags API
        # 2.delete above created tag using deleteTags API

        if self.zone.networkType != 'Basic':
            raise unittest.skip(
                    "No host available for migration. Skipping the test..")

        vms = VirtualMachine.list(
                                  self.apiclient,
                                  id=self.vm_1.id,
                                  listall=True
                                  )

        self.assertEqual(
                         isinstance(vms, list),
                         True,
                         "List vms should not return empty response"
                         )
        source_host = vms[0].hostid

        # Filtering out the source host from list host response
        temp_hosts = [host for host in hosts if host.id != source_host]
        dest_host = temp_hosts[0]

        self.debug("Destination host is: %s" % dest_host.id)

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )

        self.assertEqual(
                         tags[0].value,
                         'India',
                         'The tag should have original value'
                         )

        self.debug("Migrating the instance from: %s to %s" %
                                                (source_host, dest_host.id))
        self.vm_1.migrate(self.apiclient, hostid=dest_host.id)

        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_13_tag_case(self):
        """ Test Delete tags on UserVM
        """
        # Validate the following
        # 1.Create  a tag on VM using createTags API
        # 2.delete above created tag using deleteTags API

        self.debug("Creating a tag for user VM")
        tag_1 = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag_1.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )

        self.assertEqual(
                         tags[0].value,
                         'India',
                         'The tag should have original value'
                         )
        self.debug("Creating the same tag with caps for user VM")
        tag_2 = Tag.create(
                         self.apiclient,
                         resourceIds=1,
                         resourceType='userVM',
                         tags={'REGION': 'INDIA'}
                         )
        self.debug("Tag created: %s" % tag_2.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='REGION',
                        value='INDIA'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'INDIA',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag_1.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )

        self.debug("Deleting the created tag..")
        try:
            tag_2.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'REGION': 'INDIA'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='REGION',
                        value='INDIA'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_14_special_char_mutiple_tags(self):
        """ Test multiple tags and with special characters on same machine
        """
        # Validate the following
        # 1.create more than 10 tags to VM using createTags API
        # 2.Create  a tag with special characters on VM using createTags API

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                            self.apiclient,
                            resourceIds=self.vm_1.id,
                            resourceType='userVM',
                            tags={
                                    'region': 'India',
                                    'offering': 'high',
                                    'type': 'webserver',
                                    'priority': 'critical',
                                    'networking': 'advanced',
                                    'os': 'centos',
                                    'backup': 'no$required',
                                    'rootvolume': 'NFS',
                                    'iso': 'na',
                                    'ha': 'yes',
                                    'test': 'test'
                               }
                         )
        self.debug("Tags created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'India',
                         'The tag should have original value'
                         )
        # Cleanup
        tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={
                             'region': 'India',
                             'offering': 'high',
                             'type': 'webserver',
                             'priority': 'critical',
                             'networking': 'advanced',
                             'os': 'centos',
                             'backup': 'no$required',
                             'rootvolume': 'NFS',
                             'iso': 'na',
                             'ha': 'yes',
                             'test': 'test'
                             }
                       )
        return

    @attr(tags=["advanced"])
    def test_15_project_tag(self):
        """ Test create and delete project tag
        """
        # Validate the following
        # 1.Create  a New project by cliking on "New Project"
        # 2.Create a tag on projects using createTags API

        # Create project as a domain admin
        project = Project.create(
                                 self.apiclient,
                                 self.services["project"],
                                 account=self.account.account.name,
                                 domainid=self.account.account.domainid
                                 )
        # Cleanup created project at end of test
        self.cleanup.append(project)
        self.debug("Created project with domain admin with ID: %s" %
                                                                project.id)

        self.debug("Creating a tag for the project")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=project.id,
                         resourceType='project',
                         tags={'team': 'dev'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='project',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='team',
                        value='dev'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'dev',
                         'The tag should have original value'
                         )
        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=project.id,
                       resourceType='project',
                       tags={'team': 'dev'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='project',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='team',
                        value='dev'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        return

    @attr(tags=["advanced", "basic"])
    def test_16_query_tags_other_account(self):
        """ Test Query the tags of other user account resources
        """
        # Validate the following
        # 1.login with an account(account A)
        # 2.create a tags on resource(eg:VM)
        # 3. login with another account(Account b) and query the tags using
        #    listTags API

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        self.debug("Creating an admin and user accounts..")
        admin_account = Account.create(
                            self.apiclient,
                            self.services["account"],
                            admin=True,
                            domainid=self.domain.id
                            )

        user_account = Account.create(
                            self.apiclient,
                            self.services["account"],
                            domainid=self.domain.id
                            )
        self.cleanup.append(admin_account)
        self.cleanup.append(user_account)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=admin_account.account.name,
                        domainid=admin_account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'India',
                         'The tag should have original value'
                         )
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=user_account.account.name,
                        domainid=user_account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )
        self.assertEqual(
                         tags[0].value,
                         'India',
                         'The tag should have original value'
                         )
        # cleanup
        tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        return

    @attr(tags=["advanced", "basic"])
    def test_17_invalid_list_parameters(self):
        """ Test listAPI with invalid tags parameter
        """
        # Validate the following
        # 1.Create a tag on  supported resource type(ex:Volume)
        # 2..Run the list API commands  with passing invalid key parameter

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        self.debug("Passing invalid parameteres to the listTags API")

        with self.assertRaises(Exception):
            Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='listUserVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        # cleanup
        tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        return

    def test_18_delete_add_same_tag(self):
        """ Test deletion and addition of same tag on a resource.
        """

        # Validate the following
        # 1. Deletion of a tag without any errors.
        # 2. Add same tag.

        self.debug("Creating a tag for user VM")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )

        self.assertEqual(
                              tags[0].value,
                              "India",
                              "Tag created with incorrect value"
                              )

        self.debug("Deleting the created tag..")
        try:
            tag.delete(
                       self.apiclient,
                       resourceIds=self.vm_1.id,
                       resourceType='userVM',
                       tags={'region': 'India'}
                       )
        except Exception as e:
            self.fail("Failed to delete the tag - %s" % e)

        self.debug("Verifying if tag is actually deleted!")
        tags = Tag.list(
                        self.apiclient,
                        listall=True,
                        resourceType='userVM',
                        account=self.account.account.name,
                        domainid=self.account.account.domainid,
                        key='region',
                        value='India'
                        )
        self.assertEqual(
                         tags,
                         None,
                         "List tags should return empty response"
                         )
        self.debug("Recreating the tag with same name")
        tag = Tag.create(
                         self.apiclient,
                         resourceIds=self.vm_1.id,
                         resourceType='userVM',
                         tags={'region': 'India'}
                         )
        self.debug("Tag created: %s" % tag.__dict__)

        self.assertEqual(
                         isinstance(tags, list),
                         True,
                         "List tags should not return empty response"
                         )

        self.assertEqual(tags[0].value,
                         "India",
                         "Tag created with incorrect value"
                         )
        return

